version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"  # Map the container's port 80 to host port 5173 for frontend
      - "4000:4000"